server:
  port: 8080
  address: 0.0.0.0

spring:
  profiles:
    active: local

  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

user:
  service:
    #url: ${USER_SERVICE_URL}
    url: http://localhost:8080

product:
  service:
    #url: ${PRODUCT_SERVICE_URL}
    url: http://localhost:8080